name: Cache Test

on:
  workflow_dispatch:

jobs:
  cache-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: prime-cache-4b53ccf
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/my-cache
          key: cache-4b53ccf

      - name: Echo cache result
        run: |
          echo "Cache hit? ${{ steps.cache-step.outputs.cache-hit }}"
